---
title: "Summary page"
date: '(`r format(Sys.time(), format = "%Y-%m-%d")`)'
output:
  flexdashboard::flex_dashboard:
    vertical_layout: scroll
    source_code: embed
    theme: cosmo
    self_contained: no
---

Quality control  {data-orientation=rows data-icon="fa-area-chart"}
================================
  
Row
-------------------------------------

### Overview and Summary Information

```{r setup, include = FALSE}
library(DT)
library(dplyr)
library(tibble)
library(formattable)
knitr::opts_chunk$set(echo = FALSE, 
                      message = FALSE,
                      warning = FALSE)
options(stringsAsFactors = F)
```

```{r }
options(stringsAsFactors = F)
info_table <- read.table("final_table_source.txt", sep = "\t", header = T)
info_table[info_table[, "TPM5p"]=="-", "TPM5p"] <- "0"
info_table[info_table[, "TPM3p"]=="-", "TPM3p"] <- "0"
info_table$Mean <- round(info_table$Mean, 2)
info_table$Max <- round(info_table$Max, 2)

colname_list <- c("ID", "HTcriteria", "One_class_SVM", "Genomic_source","Source","Stem_loop_loc", "Stem_loop_len", "Stem_loop_MFE", "Stem_loop_AMFE",
                     "Mature_arm", "Seq5p", "Len5p", "TPM5p", "The_number_of_sequences_in_pre.miRNAs", "Abundance_bias", "Strand_bias",
                     "RNAfold", "Centroidfold", "Mean", "Max", "Samples")
df <- info_table[, colname_list]

replaceCol <- c("Mature_arm", "Seq5p", "Len5p", "TPM5p")
for(i in 1:nrow(df)){
  if(info_table[i, "Mature_arm"]=="5p"){
    df[i, replaceCol] <- info_table[i, replaceCol]
  } else if(info_table[i, "Mature_arm"]=="3p"){
    df[i, replaceCol] <- info_table[i, c("Mature_arm", "Seq3p", "Len3p", "TPM3p")]
  } else {
    if(as.numeric(info_table[i, "TPM5p"])>=as.numeric(info_table[i, "TPM3p"])){
      df[i, replaceCol] <- c('5p', info_table[i, c("Seq5p", "Len5p", "TPM5p")])
    }else{
      df[i, replaceCol] <- c('3p', info_table[i, c("Seq3p", "Len3p", "TPM3p")])
    }
  }
}


# df <- read.table("summary_information.txt", sep = "\t", header = T)
#tissue_name <- colnames(info_table)[33:ncol(info_table)]
linkname <- gsub(":", "-", info_table$Extended_stem_loop_loc)
# for(i in 1:nrow(df)){
#  df_out <- data.frame("name" = colnames(df),  "value" = as.character(df[i,]))
#   writeLines(jsonlite::toJSON(df_out), paste0("data/", linkname[i], ".json"))
# }
df[,1] <- paste0("<a href=\"javascript:void(0)\" onclick=\"mirnaplot('",linkname,"')\">", df[,1],"</a>")

# set_list <- lapply(1:3,function(cc){
#   formatter("span", style = x ~ style(color = ifelse(x, "green", "red")),
#             x ~ icontext(ifelse(x, "ok", "remove"), ifelse(x, "Yes", "No")))
# })
# names(set_list) <- colnames(df)[c(2,16,17)]

df <- cbind(df, "remove" = '<input type="button" value="Delete" class="btnDelete">')
df <- df %>% rowid_to_column("Row") %>% mutate(Row = "")
# df <- formattable(df, set_list)

th_style = "padding: 5px;
color: #fff;
background-color:#517FB9;
text-align: center;
border-right-width: 1px; 
border-right-style: solid; 
border-right-color: white; 
border-bottom-width: 1px; 
border-bottom-style: solid; 
border-bottom-color: white;
word-wrap: break-word;      
overflow-wrap: break-word;"

table_frame <-
  function() {
    htmltools::withTags(
      table(class = 'display', style = "padding: 1px; font-size: 0.8em; 
            font-family: sans-serif; text-align: center; word-wrap: break-word; overflow-wrap: break-word;",
            thead(tr(
              th(rowspan = 2, style = th_style, 'Row'),
              th(rowspan = 2, style = th_style, 'ID'),
              th(rowspan = 2, style = th_style, 'HT criteria'),
              th(rowspan = 2, style = th_style, 'One class SVM'),
              th(rowspan = 2, style = th_style, 'Genomic source'),
              th(rowspan = 2, style = th_style, 'Source'),
              th(class = 'dt-center', style = th_style, colspan = 4, 'Stem loop'),
              th(class = 'dt-center', style = th_style, colspan = 4, 'Mature miRNA'),
              th(class = 'dt-center', style = th_style, colspan = 5, 'miRNA precursor'),
              th(class = 'dt-center', style = th_style, colspan = 3, 'Expressed samples'),
              th(rowspan = 2, style = th_style, 'Remove'),
              tr(lapply(c('Loc', 'Len', 'MFE', 'AMFE', 'Arm', 'Seq', 'Len', 'TPM',
                  'Seq count', 'Abundance bias', 'Strand bias',
                  'RNAfold', 'Centroidfold','Mean','Max','Sample(TPM>1)'), th, style = th_style)) #'Mean', 'Max','Sample (TPM>1)', tissue_name
            )
          )))
  }

#th(class = 'dt-center', style = th_style, colspan = 3, 'TPM in 1063 samples'), 
#th(class = 'dt-center', style = th_style, colspan = length(tissue_name), 'TPM in tissues'), 

table_options <- function() {
  list(dom = 'Bfrtip',
    pageLength = 20,
    buttons = list(c('copy', 'csv', 'excel', 'pdf', 'print')),
    columnDefs = list(list(className = "select-checkbox", targets = 0, orderable = FALSE)),
    select = list(style = "multi", selector = "td:first-child"),
    searchHighlight = TRUE,
    scrollX = TRUE,
    fixedColumns = TRUE,
    extensions = 'Responsive',
    deferRender = TRUE,
    scroller = TRUE,
    lengthChange = FALSE,
    initComplete = JS(
      "function(settings, json) {",
      "$(this.api().table().header()).css({'background-color': '#517fb9', 'color': '#fff'});",
      "}"
    )
      )
}

#brks <- quantile(df[,tissue_name], probs = seq(.05, .95, .05), na.rm = TRUE)
#clrs <- round(seq(255, 40, length.out = length(brks) + 1), 0) %>%
#{paste0("rgb(255,", ., ",", ., ")")}

df$One_class_SVM <- factor(df$One_class_SVM, levels = unique(df$One_class_SVM))
df$Source <- factor(df$Source, levels = unique(df$Source))
df$Genomic_source <- factor(df$Genomic_source, levels = unique(df$Genomic_source))

datatable(
  df,
  rownames = FALSE,
  editable = FALSE,
  elementId = "linktable",
  class="compact cell-border",
  filter = 'top',
  # class = 'cell-border',
  escape = FALSE,
  container = table_frame(),
  options = table_options(),
  extensions = c('Buttons', 'Select'),
  callback = JS("$('#linktable tbody').on('click','.btnDelete',function(){table.row( $(this).parents('tr') ).remove().draw();});")) %>% 
  formatStyle("Genomic_source", backgroundColor = styleEqual(unique(df$Genomic_source), c("lightblue", "lightgreen", "lightpink", "lightgrey", "lightred", "lightyellow")[1:length(unique(df$Genomic_source))]))
```

> The table displays the overview information of Precursor miRNAs. Each row presents one candidate pre-miRNAs with name, location in genome, strand information, abundance, and bias.

```{js}
function mirnaplot(event){
  window.open("miRNA_out/" + event +".html");
}
```
